### ISSUE TITLE
How to get AUTH_URL and AUTH_PWD

### ISSUE THREAD

**Issue by lalitsparx** [sightcall/Android-Tutorials#1]
Hi I am new to sightcall.com and developing a demo using your tutorial. So in order to do so I need to have the auth url and password where can I get that. I have create an account in sightcall where I am only able to see the App_id.

**Comment by RomainGabriel** [comment]
Hi there,
You would first need to build an authentication client. This will become your auth_url.
I would suggest to go through our "Quick start" tutorial, even if you're not interested in our JS SDK. It will help you understanding how the authentication works: https://docs.sightcall.com/GD/01_javascript/01_jsquickstart.html

For further requests, please contact the SightCall support team directly from your https://saportal.sightcall.com account, "Help" tab. 

Regards.

**Comment by lalitsparx** [comment]
Thanks for the answer. As suggested by I have got the auth_url and auth_pwd but still I am getting the error

java.lang.ExceptionInInitializerError
at net.rtccloud.sdk.Rtcc.getEngineStatus(Unknown Source)
com.example.sightcallvideochatdemo.MainActivity.invalidateActionBar(MainActivity.java:117)



![image](https://cloud.githubusercontent.com/assets/13553361/8982609/b51a3fd4-36e0-11e5-9bfa-935a6e5ecab2.png)

![capture](https://cloud.githubusercontent.com/assets/13553361/8982621/cb07daa4-36e0-11e5-8be2-87b576331f88.PNG)

Kindly help me

**Comment by RomainGabriel** [comment]
Hi there,
I answered this request couple of minutes ago via the SightCall support (as explained in the README, we recommend to use Android Studio). Please stop using Github for that kind of request. Contact the SightCall support team directly from your https://saportal.sightcall.com account, "Help" tab instead.
Regards.
